name: StackHawk Actions
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo!
        uses: actions/checkout@v2
      
      # Install Docker and Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      # Build and Run the Application
      - name: Build and Run Vulny!
        run: docker-compose build && docker-compose up -d
      
      # Run HawkScan
      - name: HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk-actions.yml
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
